spring:
  profiles:
    active:
      - dev
dofizjo:
  security:
    attemptLimit: 10

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
  ssl:
    enabled: false
    key-store: classpath:keystore/keys.jks
    key-store-password: t3stp4ss
    key-password: t3stp4ss
    key-alias: dofizjo

---
spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: never
  datasource:
    url: ${CLEARDB_DATABASE_URL}
    username: ${CLEARDB_DATABASE_USERNAME}
    password: ${CLEARDB_DATABASE_PASSWORD}

# Using Heroku ssl certificates
# https://devcenter.heroku.com/articles/understanding-ssl-on-heroku#when-to-use-heroku-ssl